### PR TITLE
Fix URLs in feed.xml.

### PR DESCRIPTION
**Pull request by gxrneyme**
The URLs in feed.xml pointed to an incorrect domain so I've fixed it.

### CODE REVIEW

**Comment by SimonPadbury** [comment]
Thankyou !

**Comment by gxrneyme** [comment]
No trouble at all! Thanks for the great posts.

**Comment by SimonPadbury** [comment]
A major improvement on my Codebase [https://github.com/SimonPadbury/Codebase](https://github.com/SimonPadbury/Codebase) will be launched, hopefully this month. In case you're interested in SASS and Pug.

**Comment by gxrneyme** [comment]
Excellent, thanks Simon!

**Pull request merged**
